# Generated by Django 3.2.13 on 2022-07-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220702_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='stages',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
